### ISSUE TITLE
Method 'call' in 'GrapeSwagger::Entity::Parser' model is not compatible with new version of gem grape-entity 0.6.0

### ISSUE THREAD

**Issue by thomas-peyric** [ruby-grape/grape-swagger-entity#14]
When I use the last version of grape-entity (0.6.0) the parser always return nil for all models

I think error is here : 
```ruby
def call
  # TODO: this should only be a temporary hack ;)
  if ::GrapeEntity::VERSION =~ /0\.4\.\d/
    parameters = model.exposures ? model.exposures : model.documentation
  elsif ::GrapeEntity::VERSION =~ /0\.5\.\d/
    parameters = model.root_exposures.each_with_object({}) do |value, memo|
      memo[value.attribute] = value.send(:options)
    end
  end
  parse_grape_entity_params(parameters)
end
```
variable 'parameters' is always nil with new version of grape-entity

**Comment by Bugagazavr** [comment]
@LeFnord can we drop 0.4 versions support?

**Comment by LeFnord** [comment]
Will have a look this evening, I'm on the way

**Comment by dblock** [comment]
I definitely think we can drop support for a 0.4.x version, PR welcome.

**Comment by dblock** [comment]
This could also just be fixed by changing the second `if` to be future-proof for all versions to an `else`. Maybe more user-friendly.

**Comment by Bugagazavr** [comment]
@dblock yes this is fast fix:

```rb
def call
  # TODO: this should only be a temporary hack ;)
  if ::GrapeEntity::VERSION =~ /0\.4\.\d/
    parameters = model.exposures ? model.exposures : model.documentation
  else
    parameters = model.root_exposures.each_with_object({}) do |value, memo|
      memo[value.attribute] = value.send(:options)
    end
  end
  parse_grape_entity_params(parameters)
end
```

**Comment by Bugagazavr** [comment]
0.1.5 version released

**Comment by LeFnord** [comment]
thanks @Bugagazavr not to drop 0.4, think dropping it, is not needed here,
but I plan drop dependencies for grape-swagger: grape-entity < 0.5, grape < 0.16 → cleaning-up the gem and add support for ruby 2.4, actual there is a ruby 2.4 branch on my fork, and it looks fine, besides danger, it depends on ox and this fails with ruby 2.4
