### ISSUE TITLE
Support examples

### ISSUE THREAD

**Issue by Kukunin** [ruby-grape/grape-swagger-entity#27]
OpenAPI 2 and 3 versions has support of settings examples for definition properties. https://swagger.io/docs/specification/2-0/adding-examples/

That'd be cool to have support them: 

      expose :username, documentation: {required: true, example: 'John Smith'}

**Comment by Bugagazavr** [comment]
Hi, looks good, feel free to create pull request.

**Comment by Kukunin** [comment]
Can be closed

**Comment by Bugagazavr** [comment]
Released in 0.2.2
