### ISSUE TITLE
Swagger doesn't respect `root` from `grape-entity`

### ISSUE THREAD

**Issue by Kukunin** [ruby-grape/grape-swagger-entity#29]
`grape-swagger` has [a possibility](https://github.com/ruby-grape/grape-entity#collection-exposure) to set `root` for an Entity. 

But it's ignored in Swagger document.

**Comment by Kukunin** [comment]
Current workaround is to use a wrapper Entity instead of `root` directive

**Comment by Kukunin** [comment]
Actually, that's better avoid the `root` directive, since the same entity might be included into other entity or be rendered directly in the root of a response. I created wrapper entity that adds `root` attribute and swagger works like a charm

**Comment by Bugagazavr** [comment]
Hello, i try to look to this.

**Comment by Bugagazavr** [comment]
This feature depends on context, grape-swagger don't know anything about grape execution context. As workaround you can write own parser, see example  https://github.com/ruby-grape/grape-swagger/issues/549#issuecomment-265872100
