### ISSUE TITLE
Error requiring grape-swagger-entity

### ISSUE THREAD

**Issue by mileszs** [ruby-grape/grape-swagger-entity#3]
Initially, I found the default of requiring `grape-swagger-entity` in the Gemfile caused the environment not to load (when, say, starting the server). I added `require: false` to the Gemfile. Now I can see the error below when `require 'grape-swagger-entity'` is entered in the Rails console. 

```
NoMethodError: undefined method `model_parsers' for GrapeSwagger:Module
        from /Users/mileszs/.gem/ruby/2.3.0/gems/grape-swagger-entity-0.1.2/lib/grape-swagger/entity.rb:12:in `<top (required)>'
        from /Users/mileszs/.gem/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /Users/mileszs/.gem/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/mileszs/.gem/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/mileszs/.gem/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /Users/mileszs/.gem/ruby/2.3.0/gems/grape-swagger-entity-0.1.2/lib/grape-swagger-entity.rb:1:in `<top (required)>'
        from /Users/mileszs/.gem/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /Users/mileszs/.gem/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/mileszs/.gem/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/mileszs/.gem/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from (irb):1
        from /Users/mileszs/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
        from /Users/mileszs/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
        from /Users/mileszs/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /Users/mileszs/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/mileszs/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
 ```

I am mounting Grape within Rails. My Gemfile.lock has the following versions of `grape-swagger` and `grape-swagger-entity`.

```
    grape-swagger (0.20.2)
    grape-swagger-entity (0.1.2)
      grape-swagger (>= 0.20.2)
```

I am going to attempt to further dive into the code to try to figure out where and why, and how and what. Honestly, I am hoping someone has seen this before, or sees something dumb I'm doing.

Thanks!

**Comment by mileszs** [comment]
Requiring `grape-swagger-entity` version `0.1.0` seems to have resolved this issue. I now have the following in my `Gemfile.lock`:

```
    grape-swagger (0.20.3)
    grape-swagger-entity (0.1.0)
      grape-swagger (>= 0.20.2)
```

**Comment by dblock** [comment]
So 0.1.2 introduces a regression? What is your version of Grape?

**Comment by mileszs** [comment]
My grape version is 0.16.2. Here's the result of `cat Gemfile.lock | grep
grape`:

```
    grape (0.16.2)
    grape-entity (0.5.1)
    grape-swagger (0.20.3)
      grape (>= 0.12.0)
      grape-entity
    grape-swagger-entity (0.1.0)
      grape-entity
      grape-swagger (>= 0.20.2)
      grape (~> 0.10, < 1.0)
  grape
  grape-entity
  grape-swagger
  grape-swagger-entity (= 0.1.0)
```

I believe there is a regression, or that perhaps the latest
`grape-swagger-entity` needs to require a much newer version of
`grape-swagger`. It seems that it expects there to be a
`GrapeSwagger.model_parsers` method that is available in the latest master
[here](
https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger.rb#L15),
but is not available in the latest tagged release 0.20.3.

**Comment by dblock** [comment]
@Bugagazavr I think we just need to cut a release of grape-swagger, no? Feel free to.

**Comment by Bugagazavr** [comment]
@dblock yes

**Comment by Bugagazavr** [comment]
Ok, grape-swagger 0.20.4 released, just `bundle update grape-swagger`, also I soon will release a new version `grape-swagger-entity` and `grape-swagger-representable` with minimal required grape-swagger version `0.20.4`.

**Comment by Bugagazavr** [comment]
Ok, new version of `grape-swagger-entity`, released, let me know if you have any questions.
