### ISSUE TITLE
grape-swagger 1.0.0 support

### ISSUE THREAD

**Issue by mallowlabs** [ruby-grape/grape-swagger-entity#43]
[grape-swagger-entity](https://github.com/ruby-grape/grape-swagger-entity) currently supports  `'grape-swagger', '>= 0.31.0' `.
But current newest [grape-swagger](https://github.com/ruby-grape/grape-swagger) version is `1.0.0`

I want to use newer versions  of [grape-swagger](https://github.com/ruby-grape/grape-swagger) and [grape](https://github.com/ruby-grape/grape) gem.
Can you bump the dependency version of [grape-swagger](https://github.com/ruby-grape/grape-swagger)?

**Comment by LeFnord** [comment]
??? … that's why the `>=` …it shouldn't be any problems

run it self in a project with following versions:
```
  * grape (1.3.1)
  * grape-entity (0.8.0)
  * grape-swagger (1.0.0)
  * grape-swagger-entity (0.3.4)
```

**Comment by mallowlabs** [comment]
Sorry! I misread gemspec file..
There is no problem in `grape-swagger`.
