### ISSUE TITLE
example provided with documentation ignored for type of boolean

### ISSUE THREAD

**Issue by drewnichols** [ruby-grape/grape-swagger-entity#45]
I have an entity defined as follows which provides and example value of `false`
```
module Entities
  class OrderEntity < Grape::Entity
    expose :pre_order,
           documentation: {
             type: Grape::API::Boolean,
             desc: 'true, if this order is a pre-order, otherwise false.',
             example: false
           }
  end
end
```

When the swagger file is generated it seems to be ignoring the example and returns nothing.

```
"OrderEntity": {
  "type": "object",
  "properties": {
    "pre_order": {
      "type": "boolean",
      "description": "true, if this order is a pre-order, otherwise false."
    }
  }
}
```

I should note that if I change the example to a string of `"false"` it does return the string correctly.

**Comment by drewnichols** [comment]
After fixing this I noticed that when we provide a `default` value in the documentation of false it suffers from the same problem

**Comment by Bugagazavr** [comment]
Hello, grape-swagger-entity 0.4.0 was released.
