### ISSUE TITLE
Documentation on how to use this gem

### ISSUE THREAD

**Issue by alesrosina** [ruby-grape/grape-swagger-entity#55]
I'm a bit struggling on how to use this gem - I am using only `grape-entity` gem in my project and serving api with classic rails controllers, where i just return sth like:

```rb
class ExamplesController < ActionController::Base
  def show
    render json: ExampleEntity.represent(@resource), status: :ok
  end
end
```

And `Grape::Entity` is defined like so:

```rb
class ExampleEntity < Grape::Entity
  expose :some_filed, documentation: { type: 'string', desc: 'Most important filed', required: true }
  expose :second_filed, documentation: { type: 'string', desc: 'Not so important stuff', required: false }
  expose :more_stuff, using: MoreStuffEntity, documentation: {  desc: 'more things with child entity', param_type: 'body', is_array: false }
end
```

And then obviously, i also set routes in `config/routes.rb`,m sth like:

```rb
namespace :api, defaults: { format: :json } do
  resources :examples, only: [:show]
end
```

Is there any chance I can use this gem to generate swagger docs from my setup? And if so, how? 

Thank you for your help.

PS: This is more like a question and - issue would be a not so clear readme on this topic, how to use this one outside of `grape` gem.

**Comment by LeFnord** [comment]
in general, please use the [Google Group](https://groups.google.com/g/ruby-grape) for questions.

besides that, if I understand you correct, then you want to add swagger documentation, right?  
if it is so, please start with [grape-swagger usage](https://github.com/ruby-grape/grape-swagger#usage-)

**Comment by alesrosina** [comment]
Perfect, thanks for reply. I will try over there.

I guess I can close this issue then.
