### ISSUE TITLE
New release with latest bug fixes?

### ISSUE THREAD

**Issue by Jell** [ruby-grape/grape-swagger-entity#73]
Version 0.5.4 of this gem introduced a bug that is generating invalid OpenAPI docs when using enum values on array attributes (this was working in version 0.5.3).

A fix has been merged earlier this year but has not yet been released:

https://github.com/ruby-grape/grape-swagger-entity/pull/71#issuecomment-2116985790

Would it be possible to cut a new release to avoid issues for new users and allow existing users to upgrade without breaking their existing setup?

**Comment by dblock** [comment]
I released 0.5.5.
